  version: '3.3'
  services:
    api:
      build:
        context: ./api
        dockerfile: Dockerfile
      ports:
        - '3000:3000'
      depends_on:
        - couchbase
        - celery
      volumes:
        - ./api:/app
        - /app/node_modules
    couchbase:
      image: couchbase:enterprise-6.0.2
      ports:
        - '8091-8096:8091-8096'
        - '11210-11211:11210-11211'
      volumes:
        - ./couchbase/local_data:/opt/couchbase/var
    redis:
      image: redis
      ports:
        - '6379:6379'
    celery:
      build:
        context: ./celery
        dockerfile: Dockerfile
      depends_on:
        - redis
        - flower
    flower:
      image: mher/flower
      ports:
        - '5555:5555'
      depends_on:
        - redis
      environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
      - FLOWER_BASIC_AUTH=root:tBvsAHF7ZsVPPrYc
    python:
      build:
        context: ./python
        dockerfile: Dockerfile
      volumes:
        - ./python/src:/app
      depends_on:
        - celery
        - flower
      command: bash -c "while true; do sleep 1; done"